access_token = '24bf603b-3da3-48a1-9a87-1f80c102b701'
device_id = '4bc3a9d4-549f-4055-8c17-6626c42ee10b'
license_key = '80u9PSb7-O165Zu7s-b3w1R79Y'
private_key = 'gJvnP7D7EuQQhPMOa5Agtk8XHOfvQXJF/MAn6taA+VM='
